### ISSUE TITLE
add nixos module for polkadot node service

### ISSUE THREAD

**Issue by andresilva** [andresilva/polkadot.nix#1]

**Comment by dzmitry-lahoda** [comment]
we use process-compose. works super awesome.

**Comment by dzmitry-lahoda** [comment]
as parity bridge dev you may interest  https://github.com/paritytech/zombienet/blob/08b9f5f4722f2595b6fb4877f290b3c76621ed42/flake-module.nix#L182

if any ETH thing - feel free to join chat.

**Comment by andresilva** [comment]
This is provided by https://github.com/sporyon/dotnix-core/.
