### ISSUE TITLE
added runtime versions as they are deployed to rococo/wococo/westend/polkadot/kusama

### ISSUE THREAD

**Issue by dzmitry-lahoda** [andresilva/polkadot.nix#9]
More of like idea/question.

Is that possible for each release release wasm released by parity?

Is that possible for node?

One of use cases, is subxt tracking. Actually can generate subxt scale package for release ahead of time.

**Comment by dzmitry-lahoda** [comment]
another reason to run high fidelity devnets which replicate remote test and main nets as close as possible with proper relay version

**Comment by dzmitry-lahoda** [comment]
oh,

```
#[cfg(feature = "rococo-native")]
use rococo_runtime as rococo;
``` 

so cannot cannot use in devnet.... 

so kind of version of devnets of polkadot is awesome to have

**Comment by andresilva** [comment]
I am not sure exactly what this means. Closing as stale.
